#!/bin/bash
set -e
# mount cgroups
if grep -v '^#' /etc/fstab | grep -q cgroup; then
    echo 'cgroups mounted from fstab, not mounting /sys/fs/cgroup'
else
    # kernel provides cgroups?
    if [ -e /proc/cgroups ]; then
        # if we don't even have the directory we need, something else must be wrong
        if [ -d /sys/fs/cgroup ]; then
            # mount /sys/fs/cgroup if not already done
            if ! mountpoint -q /sys/fs/cgroup; then
	        mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
            fi
            cd /sys/fs/cgroup
            # get/mount list of enabled cgroup controllers
            for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
	        mkdir -p $sys
	        if ! mountpoint -q $sys; then
		    if ! mount -n -t cgroup -o $sys cgroup $sys; then
			rmdir $sys || true
		    fi
	        fi
            done
        fi
    fi
fi
# create group
getent group docker >/dev/null || groupadd -r docker

# install systemd service
if [ -d "/usr/lib/systemd" ]; then
    install -m 755 /etc/init.d/docker /usr/lib/systemd/scripts/docker
    cat <<EOF > /usr/lib/systemd/system/docker.service
[Unit]
Description=Docker

[Service]
Type=oneshot
ExecStart=/usr/lib/systemd/scripts/docker start
ExecStop=/usr/lib/systemd/scripts/docker stop
ExecRestart=/usr/lib/systemd/scripts/docker restart
ExecStatus=/usr/lib/systemd/scripts/docker status
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
    chmod 755 /usr/lib/systemd/system/docker.service
fi
